name: auto crawler

# 触发条件
on:
  # push的时候触发
  push:
    branches: main
  workflow_dispatch:
  # 定时触发
  schedule:
     - cron: '*/5 * * * *'
    # 表达式生成  https://crontab.guru/
    # 此处是UTC时间 即北京时间 -8小时
     - cron: '40 2,12 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6.7'
    - name: load cache  
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: set timezone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: install requirements
      run: |
        pip install -r requirements.txt
    - name: run main.py
      # env:
      #   CONFIG: ${{ secrets.CONFIG }}
      run: |
        python main.py
      #   echo "$CONFIG" > ./config.json
         # 使用云开发 Github Action 部署
         
#     - name: 推送到腾讯云
#       id: deployStatic
#       uses: TencentCloudBase/cloudbase-action@v1
#       with:
#         # 云开发的访问密钥 secretId 和 secretKey
#         secretId: ${{ secrets.SECRET_ID }}
#         secretKey: ${{ secrets.SECRET_KEY }}
#         # 云开发的环境id
#         envId: ${{ secrets.ENV_ID }}
#         # Github 项目静态文件的路径
#         staticSrcPath: subscribe
          
    - name: commit updates
      run: |                 
         git config --local user.email "tzztzx@outlook.com"
         git config --local user.name "david"
         git add subscribe/vmess.txt
         git commit -m "update vmess.txt"
    - name: push updates
      uses:  ad-m/github-push-action@master
      with:
         # github_token: ${{ secrets.TOKEN }}
         branch: main
